const ADDTODO = 'ADD_TODO';
const REMOVETODO = 'REMOVE_TODO';
const UPDATEHEADTITLE = "UPDATEHEADTITLE";
const UPDATEHOTELRESULT = "UPDATEHOTELRESULT";
const UPDATESEARCH = "UPDATESEARCH";

// API AUTHENTICATION
const RapidAPIKey = "33c295589fmshb08d7fdec947940p171affjsn0dc29f4dc0e5";
const RapidAPIHost = "apidojo-booking-v1.p.rapidapi.com";

export { ADDTODO, REMOVETODO, UPDATEHEADTITLE, UPDATEHOTELRESULT, UPDATESEARCH, RapidAPIKey, RapidAPIHost };